const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const ts=require('typescript');const crypto=require('node:crypto');
const compile=file=>ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;
function setup({complete=false,sendFails=false}={}){
 const records=new Map();let sends=0,analysisCalls=0;let gate=Promise.resolve();
 const message={id:'a',threadId:'t',from:'Client <client@example.com>',to:'motshirtmauritius@gmail.com',subject:'20 polos',date:'today',receivedAtMs:Date.now(),messageIdHeader:'<original@example.com>',text:'20 polos',labels:['INBOX']};
 const draft={name:'Client',email:'client@example.com',phone:'',company:'',address:'',brn:'',vat:'',deadline:'',delivery:'',printMethod:'',notes:'20 polos',lines:[{description:'polos',quantity:20}]};
 let missing=complete?[]:[{key:'phone',label:'Phone',question:'Your phone?'}];
 const snap=ref=>({exists:()=>records.has(ref),data:()=>records.get(ref)});
 const set=(ref,value,options)=>records.set(ref,options?.merge?{...records.get(ref),...value}:value);
 const firestore={doc:(_db,c,id)=>c+'/'+id,collection:()=>{},query:()=>{},where:()=>{},limit:()=>{},getDoc:async ref=>snap(ref),getDocs:async()=>({docs:[]}),serverTimestamp:()=>123,setDoc:async(...args)=>set(...args),runTransaction:async(_db,fn)=>{const previous=gate;let release;gate=new Promise(r=>release=r);await previous;try{return await fn({get:async ref=>snap(ref),set,update:(ref,value)=>set(ref,value,{merge:true})});}finally{release();}}};
 const quote={};vm.runInNewContext(compile('src/lib/email-quote.ts'),{exports:quote,Date});
 const model={};vm.runInNewContext(compile('src/lib/email-intake-model.ts'),{exports:model});
 const modules={'node:crypto':crypto,nodemailer:{createTransport:()=>({sendMail:async payload=>{sends++;assert.equal(payload.to,'client@example.com');assert.equal(payload.replyTo,'motshirtmauritius@gmail.com');assert.equal(payload.inReplyTo,'<original@example.com>');if(sendFails)throw new Error('timeout');return {accepted:[payload.to]};}})},'firebase/firestore':firestore,'@/lib/firebase':{db:{}},'./gmail-connection-store':{getSavedGmailToken:async()=>undefined},'./gmail-inbox':{INBOX_EMAIL:'motshirtmauritius@gmail.com',createGmailConnection:async()=>async()=>({threads:[{id:'t'}]}),readGmailThread:async()=>[message]},'./email-quote':quote,'./email-intake-model':model,'./email-intake-ai':{analyseEmailEnquiry:async()=>{analysisCalls++;return {classification:'enquiry',confidence:1,language:'en',summary:'20 polos',draft,items:[],missing,warnings:[]};}}};
 const exports={};vm.runInNewContext(compile('src/lib/email-intake.ts'),{exports,require:n=>{if(!modules[n])throw new Error(n);return modules[n];},process:{env:{SMTP_HOST:'smtp.test',SMTP_USER:'team@test.com',SMTP_PASS:'test'}},Date,Buffer});
 return {records,service:exports,message,async sync(){const state=records.get("integrations/email-intake");if(state) state.nextAllowedAt=0;return exports.syncEmailIntake();},get sends(){return sends;},get analysisCalls(){return analysisCalls;},completeReply(){message.id='b';missing=[];}};
}
test('incomplete enquiry stays out of quotes; complete reply creates exactly one quote',async()=>{const s=setup();await s.sync();assert.equal(s.records.has('quotes/gmail-t'),false);assert.equal(s.records.get('emailIntake/gmail-t').status,'needs_details');await s.sync();assert.equal(s.analysisCalls,1);s.completeReply();await s.sync();assert.equal(s.records.get('emailIntake/gmail-t').status,'ready');assert.equal(s.records.get('quotes/gmail-t').quote.lines[0].unitPrice,'');await s.sync();assert.equal(s.analysisCalls,2);assert.equal(s.sends,0);});
test('sending requires the reviewed version; double clicks send only one message',async()=>{const s=setup();await s.sync();const c=s.records.get('emailIntake/gmail-t');await assert.rejects(()=>s.service.sendIntakeQuestions(c.id,'stale'),/changed/);assert.equal(s.sends,0);const result=await Promise.allSettled([s.service.sendIntakeQuestions(c.id,c.version),s.service.sendIntakeQuestions(c.id,c.version)]);assert.equal(result.filter(r=>r.status==='fulfilled').length,1);assert.equal(s.sends,1);assert.equal(s.records.get('emailIntake/gmail-t').status,'waiting');});
test('ambiguous SMTP failure blocks automatic retries',async()=>{const s=setup({sendFails:true});await s.sync();const c=s.records.get('emailIntake/gmail-t');await assert.rejects(()=>s.service.sendIntakeQuestions(c.id,c.version),/could not be confirmed/);assert.equal(s.records.get('emailIntake/gmail-t').sendState,'unknown');await assert.rejects(()=>s.service.sendIntakeQuestions(c.id,c.version),/already sent/);assert.equal(s.sends,1);});
test('an existing quote is never overwritten during automatic intake',async()=>{const s=setup({complete:true});s.records.set('quotes/gmail-t',{manual:'preserve me'});await s.sync();assert.equal(s.records.get('quotes/gmail-t').manual,'preserve me');assert.equal(s.records.get('emailIntake/gmail-t').quoteId,'gmail-t');});
test('website notification copies are excluded before analysis',async()=>{const s=setup();s.message.subject='New Website Quotation from Client';await s.sync();assert.equal(s.analysisCalls,0);assert.equal(s.records.has('quotes/gmail-t'),false);});

test("email analysis is paced across repeated requests",async()=>{const s=setup();await s.sync();const result=await s.service.syncEmailIntake();assert.equal(result.cooldown,true);assert.equal(s.analysisCalls,1);});
