const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const ts=require('typescript');const crypto=require('node:crypto');
function setup({owner=true,state='x'.repeat(43),mailbox='motshirtmauritius@gmail.com',refresh=true,scope='https://www.googleapis.com/auth/gmail.readonly'}={}){
 let saved=null,fetches=0;
 const response=(location)=>({location,headers:new Headers(),cookies:{set(){}}});
 const modules={'next/server':{NextResponse:{redirect:response,json:(body,opt)=>({body,status:opt?.status})}},'next/headers':{cookies:async()=>({get:()=>({value:state})})},'node:crypto':crypto,'@/lib/admin-request':{getAdminRequestSession:async()=>owner===null?null:{isOwner:owner}},'@/lib/gmail-inbox':{INBOX_EMAIL:'motshirtmauritius@gmail.com'},'@/lib/gmail-connection-store':{saveGmailConnection:async value=>{saved=value;}}};
 const load=file=>{const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:n=>modules[n],process:{env:{GMAIL_CLIENT_ID:'client-id',GMAIL_CLIENT_SECRET:'client-secret'}},Buffer,URL,URLSearchParams,AbortSignal,fetch:async()=>{fetches++;return {ok:true,json:async()=>fetches===1?{access_token:'access',...(refresh?{refresh_token:'refresh'}:{}),scope}:{emailAddress:mailbox}};}});return exports;};
 return {start:load('app/api/admin/inbox/oauth/route.ts'),callback:load('app/api/admin/inbox/oauth/callback/route.ts'),get saved(){return saved;},get fetches(){return fetches;}};
}
const callback=(s,state='x'.repeat(43))=>s.callback.GET(new Request('https://www.mo-tshirt.mu/api/admin/inbox/oauth/callback?'+new URLSearchParams({state,code:'test-code'})));
test('only an owner can start or finish the Gmail connection',async()=>{for(const owner of [false,null]){const s=setup({owner});assert.equal((await s.start.GET()).status,403);assert.match((await callback(s)).location,/owner_required/);assert.equal(s.fetches,0);}});
test('OAuth start requests only read-only Gmail access with offline consent and fixed callback',async()=>{const s=setup();const r=await s.start.GET();assert.equal(r.location.origin,'https://accounts.google.com');assert.equal(r.location.searchParams.get('scope'),'https://www.googleapis.com/auth/gmail.readonly');assert.equal(r.location.searchParams.get('redirect_uri'),'https://www.mo-tshirt.mu/api/admin/inbox/oauth/callback');assert.equal(r.location.searchParams.get('access_type'),'offline');assert.equal(r.location.searchParams.get('state').length,43);});
test('missing, mismatched and malformed OAuth state are rejected before exchanging the code',async()=>{for(const state of ['', 'wrong','é'.repeat(43)]){const s=setup();assert.match((await callback(s,state)).location,/invalid_state/);assert.equal(s.fetches,0);}});
test('wrong Gmail account and missing scope never overwrite the saved connection',async()=>{for(const options of [{mailbox:'someone@example.com'},{scope:'openid'},{refresh:false}]){const s=setup(options);await callback(s);assert.equal(s.saved,null);}});
test('successful callback saves credentials server-side and redirects without any token',async()=>{const s=setup();const r=await callback(s);assert.equal(s.saved.refreshToken,'refresh');assert.equal(s.saved.email,'motshirtmauritius@gmail.com');assert.equal(s.saved.expiresAt,null);assert.match(r.location,/gmail=connected$/);assert(!r.location.includes('refresh'));});
