"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { ArrowRight, Check, CheckCircle2, Clock3, FileText, Inbox, Mail, MessageSquareText, Paperclip, RefreshCw, Send, Sparkles } from "lucide-react";
import { questionEmail, type EmailIntake } from "@/lib/email-intake-model";
const labels: Record<string, string> = { needs_details: "Needs details", waiting: "Waiting for client", ready: "Quote created", review: "Review enquiry", error: "Needs attention" };
const tones: Record<string, string> = { needs_details: "bg-amber-50 text-amber-800", waiting: "bg-blue-50 text-blue-800", ready: "bg-emerald-50 text-emerald-800", review: "bg-violet-50 text-violet-800" };
export default function EnquiriesPage() {
  const [enquiries, setEnquiries] = useState<EmailIntake[]>([]);
  const [selected, setSelected] = useState("");
  const [filter, setFilter] = useState("all");
  const [error, setError] = useState("");
  const [lastSync, setLastSync] = useState<string | null>(null);
  const [busy, setBusy] = useState("");
  const [loading, setLoading] = useState(true);
  const [notice, setNotice] = useState("");
  const load = useCallback(async () => {
    try {
      const response = await fetch("/api/admin/inbox/intake", { cache: "no-store" });
      const data = await response.json();
      if (!response.ok) throw new Error(data.error);
      setEnquiries(data.enquiries); setLastSync(data.lastSyncAt); setError(data.error || "");
    } catch (e) { setError(e instanceof Error ? e.message : "Could not load enquiries."); }
    finally { setLoading(false); }
  }, []);
  useEffect(() => {
    const id = new URLSearchParams(window.location.search).get("id");
    if (id) setSelected(id);
    void load();
    const timer = window.setInterval(load, 20000);
    window.addEventListener("email-intake-updated", load);
    return () => { window.clearInterval(timer); window.removeEventListener("email-intake-updated", load); };
  }, [load]);
  const act = async (action: string, intake?: EmailIntake) => {
    setBusy(action); setError(""); setNotice("");
    try {
      const response = await fetch("/api/admin/inbox/intake", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, id: intake?.id, version: intake?.version }) });
      const data = await response.json();
      if (!response.ok) throw new Error(data.error || "Please try again.");
      setNotice(action === "ask" ? "Questions sent. We’ll check the client’s reply automatically." : data.busy ? "Email checking is already running. New results will appear here." : "Email check complete.");
      await load();
    } catch (e) { await load(); setError(e instanceof Error ? e.message : "Please try again."); }
    finally { setBusy(""); }
  };
  const filtered = enquiries.filter(e => filter === "all" || e.status === filter);
  const current = filtered.find(e => e.id === selected) || filtered[0];
  const preview = current ? questionEmail(current) : null;
  const count = (status: string) => enquiries.filter(e => e.status === status).length;
  return <main className="mx-auto max-w-[1500px] p-4 text-slate-900 md:p-8">
    <div className="mb-5 flex flex-wrap items-center justify-between gap-3"><nav aria-label="Inbox views" className="flex gap-1 rounded-xl bg-slate-100 p-1 text-sm"><Link className="rounded-lg px-4 py-2 text-slate-500" href="/admin/inbox">All email</Link><span className="rounded-lg bg-white px-4 py-2 font-semibold shadow-sm">Enquiries</span></nav><Link href="/admin/quotation-approval" className="flex items-center gap-2 text-sm font-semibold">Quotes &amp; invoices <ArrowRight size={16} /></Link></div>
    <header className="relative overflow-hidden rounded-3xl bg-[#12372b] p-6 text-white md:p-8">
      <div className="absolute -right-12 -top-24 h-80 w-80 rounded-full border-[45px] border-white/5" />
      <div className="relative flex flex-wrap items-start justify-between gap-5"><div><p className="mb-3 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.18em] text-emerald-200"><Sparkles size={15} /> Your email assistant</p><h1 className="text-3xl font-semibold tracking-tight md:text-4xl">From inbox to quotation.</h1><p className="mt-3 max-w-xl text-sm leading-6 text-emerald-50/75">Client details come together here. Send the missing questions in one click; complete enquiries appear in Quotes &amp; invoices automatically.</p></div><button onClick={() => act("sync")} disabled={!!busy} className="flex items-center gap-2 rounded-xl bg-white/10 px-4 py-3 text-sm font-semibold hover:bg-white/20 disabled:opacity-50"><RefreshCw size={16} className={busy === "sync" ? "animate-spin" : ""} /> {busy === "sync" ? "Checking email…" : "Check email now"}</button></div>
      <div className="relative mt-7 flex flex-wrap gap-3 text-xs text-emerald-50/80">{[[Mail, "01  Read enquiry"], [MessageSquareText, "02  Collect details"], [FileText, "03  Create quote"]].map(([Icon, title], i) => { const StepIcon = Icon as typeof Mail; return <div key={i} className="flex items-center gap-3"><span className="flex items-center gap-2 rounded-full border border-white/15 px-3 py-2"><StepIcon size={14} />{title as string}</span>{i < 2 && <ArrowRight size={13} />}</div>; })}</div>
    </header>
    <div className="my-5 grid grid-cols-2 gap-3 xl:grid-cols-4">{[{ status: "needs_details", icon: MessageSquareText, title: "Need your click", caption: "Questions ready to send" }, { status: "waiting", icon: Clock3, title: "With the client", caption: "Watching for their reply" }, { status: "ready", icon: CheckCircle2, title: "Quotes created", caption: "Ready for pricing" }, { status: "review", icon: Inbox, title: "For your review", caption: "Intent needs a human check" }].map(({ status, icon: Icon, title, caption }) => <button key={status} onClick={() => setFilter(filter === status ? "all" : status)} aria-pressed={filter === status} className={`rounded-2xl border bg-white p-4 text-left transition hover:shadow-sm ${filter === status ? "border-emerald-700 ring-1 ring-emerald-700" : "border-slate-200"}`}><div className="flex items-center justify-between"><Icon size={19} className="text-slate-400" /><span className="text-3xl font-semibold tracking-tight">{count(status)}</span></div><p className="mt-3 text-sm font-semibold">{title}</p><p className="mt-1 text-xs text-slate-500">{caption}</p></button>)}</div>
    {error && <p role="alert" className="mb-4 rounded-xl bg-amber-50 p-4 text-sm text-amber-900">{error}</p>}
    {notice && <p role="status" className="mb-4 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-900">{notice}</p>}
    <div className="mb-3 flex flex-wrap items-center justify-between gap-2 text-xs text-slate-500"><button onClick={() => setFilter("all")} className="font-semibold text-slate-700">{filter === "all" ? "All enquiries" : `← All enquiries · ${labels[filter]}`} ({filtered.length})</button><span>{lastSync ? `Last checked ${new Date(lastSync).toLocaleString()}` : "First email check in progress…"} · Recent 90 days</span></div>
    <div className="grid min-h-[480px] overflow-hidden rounded-2xl border border-slate-200 bg-white lg:grid-cols-[340px_minmax(0,1fr)]">
      <section aria-label="Client enquiries" className="max-h-[780px] overflow-auto border-b border-slate-200 lg:border-b-0 lg:border-r">{loading ? <p className="p-7 text-sm text-slate-500">Loading enquiries…</p> : !filtered.length ? <div className="p-7 text-sm leading-6 text-slate-500"><Inbox className="mb-3" />No enquiries in this view yet. Incoming emails are checked automatically; the first scan works through recent conversations in batches.</div> : filtered.map(e => <button key={e.id} onClick={() => { setSelected(e.id); setNotice(""); }} aria-pressed={current?.id === e.id} className={`block w-full border-b border-slate-100 p-5 text-left transition ${current?.id === e.id ? "bg-emerald-50/70 shadow-[inset_3px_0_0_#047857]" : "hover:bg-slate-50"}`}><div className="flex items-start justify-between gap-2"><p className="truncate font-semibold">{e.draft.name || e.email}</p><span className="shrink-0 text-[10px] text-slate-400">{new Date(e.lastReplyAt).toLocaleDateString(undefined, { day: "numeric", month: "short" })}</span></div><p className="mt-1 truncate text-xs text-slate-500">{e.draft.company || e.email}</p><p className="my-3 line-clamp-2 text-sm leading-5">{e.subject}</p><span className={`rounded-full px-2.5 py-1 text-[11px] font-semibold ${tones[e.status] || "bg-slate-100"}`}>{labels[e.status]}</span>{e.status === "needs_details" && <span className="ml-2 text-[11px] text-slate-400">{e.missing.length} questions</span>}</button>)}</section>
      {current && preview ? <section aria-label="Enquiry details" className="min-w-0 p-5 md:p-7"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-medium uppercase tracking-wider text-emerald-700">Client enquiry</p><h2 className="mt-2 break-words text-xl font-semibold">{current.subject}</h2><p className="mt-2 break-words text-sm text-slate-500">{current.email}</p></div><span className={`rounded-full px-3 py-1.5 text-xs font-semibold ${tones[current.status] || "bg-slate-100"}`}>{labels[current.status]}</span></div><p className="my-5 text-sm leading-6 text-slate-600">{current.summary}</p>
        <div className="grid grid-cols-2 gap-3 rounded-xl bg-slate-50 p-4 text-sm sm:grid-cols-3">{[["Contact", current.draft.name], ["Phone", current.draft.phone], ["Company", current.draft.company], ["Required date", current.draft.deadline], ["Delivery", current.draft.delivery], ["Address", current.draft.address]].map(([label, value]) => <div key={label}><p className="text-[11px] text-slate-500">{label}</p><p className={`mt-1 break-words ${value ? "font-medium" : "text-amber-700"}`}>{value || "Not provided"}</p></div>)}</div>
        {current.items.length > 0 && <div className="my-5 space-y-2"><h3 className="text-sm font-semibold">Requested products</h3>{current.items.map((item, i) => <div key={i} className="flex items-start gap-3 rounded-xl border border-slate-200 p-3"><span className="rounded-lg bg-slate-100 px-2.5 py-1 text-sm font-semibold">{item.quantity || "?"}×</span><div className="min-w-0"><p className="text-sm font-medium">{item.product || "Product to confirm"}</p><p className="mt-1 break-words text-xs leading-5 text-slate-500">{[item.colour, item.sizes, item.printMethod, item.placement, item.artwork].filter(Boolean).join(" · ")}</p></div></div>)}</div>}
        {current.attachmentNames.length > 0 && <p className="my-4 flex items-start gap-2 text-xs text-slate-500"><Paperclip size={14} className="shrink-0" />Attachments: {current.attachmentNames.join(", ")} · Files need visual review in Gmail.</p>}
        {current.status === "ready" ? <div className="my-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><CheckCircle2 className="mb-3 text-emerald-700" /><h3 className="font-semibold text-emerald-900">Your quote is ready for pricing</h3><p className="mt-2 text-sm text-emerald-800">The client’s details and product lines are already in Quotes &amp; invoices. Prices are left for you to set.</p><Link className="mt-4 inline-flex items-center gap-2 rounded-xl bg-emerald-800 px-4 py-3 text-sm font-semibold text-white" href={`/admin/quotation-approval?quoteId=${encodeURIComponent(current.quoteId || current.id)}`}>Open quote <ArrowRight size={16} /></Link></div> : current.status === "review" ? <div className="my-5 rounded-xl bg-violet-50 p-4 text-sm leading-6 text-violet-900">This email’s buying intent is uncertain. Review the original conversation below before creating a quote manually from All email.</div> : <div className="my-5 overflow-hidden rounded-2xl border border-amber-200"><div className="bg-amber-50/70 p-4"><h3 className="flex items-center gap-2 font-semibold"><MessageSquareText size={18} />{current.status === "waiting" ? "Questions sent · waiting for their reply" : "Here’s what to ask"}</h3><p className="mt-1 text-xs leading-5 text-slate-600">{current.status === "waiting" ? "Their reply will be checked automatically. A complete enquiry moves straight into Quotes & invoices." : `${current.missing.length} missing details. This exact email will be sent when you press the button.`}</p></div><div className="p-4"><p className="break-words text-xs text-slate-500">To: {preview.to}<br />Subject: {preview.subject}</p><pre className="my-4 max-h-80 overflow-auto whitespace-pre-wrap font-sans text-sm leading-6 text-slate-700">{preview.text}</pre>{current.sendState === "unknown" || current.sendState === "sending" ? <p role="status" className="rounded-xl bg-amber-50 p-3 text-sm text-amber-900">{current.sendState === "unknown" ? "Delivery is unconfirmed. Check Gmail Sent; sending again is blocked to avoid duplicates." : "Sending has started. Refresh to check delivery; repeat sending is blocked."}</p> : current.status === "waiting" ? <p className="flex items-center gap-2 text-sm font-medium text-emerald-700"><Check size={16} />Sent {current.sentAtIso ? new Date(current.sentAtIso).toLocaleString() : ""}</p> : <button disabled={!!busy || !current.missing.length} onClick={() => act("ask", current)} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[#12372b] px-4 py-3 text-sm font-semibold text-white hover:bg-emerald-900 disabled:opacity-50 sm:w-auto"><Send size={15} />{busy === "ask" ? "Sending questions…" : "Send these questions to client"}</button>}</div></div>}
        {current.warnings.map(w => <p key={w} className="my-3 text-xs text-amber-800">{w}</p>)}<details className="mt-5 border-t border-slate-100 pt-4"><summary className="cursor-pointer text-sm font-medium text-slate-500">Original client conversation</summary><pre className="mt-4 max-h-96 overflow-auto whitespace-pre-wrap break-words font-sans text-xs leading-6 text-slate-600">{current.originalText}</pre></details>
      </section> : <div className="flex flex-col items-center justify-center p-10 text-center text-slate-400"><Mail size={36} /><p className="mt-4 text-sm">Your next client enquiry will appear here.</p></div>}
    </div><p className="mt-4 text-xs leading-5 text-slate-500">Background checks are scheduled every five minutes (scheduler delays are possible), plus checks while the admin is open and a daily fallback. Website form copies are excluded. Attachments are listed; their contents are not extracted. Emails are sent only when you press Send.</p>
  </main>;
}
